package fr.maxlego08.zregions.common.flag;

import java.util.Map;

/**
 * The English fallback description of every built-in flag, shown in the {@code /rg
 * flags} catalogue (as a MiniMessage hover) and in the zMenu flag editor lore.
 * Localised overrides live under {@code flags.<key>} in each language's messages.yml;
 * a missing key falls back to the text here, so the catalogue is never blank.
 *
 * <p>Plain text only (no colour tags): the display layer applies the palette.</p>
 */
public final class FlagDescriptions {

    private static final Map<String, String> BY_KEY = Map.ofEntries(
            Map.entry("block-break", "Prevents breaking blocks."),
            Map.entry("block-place", "Prevents placing blocks."),
            Map.entry("interact", "Prevents right-clicking non-container blocks like doors, buttons and levers."),
            Map.entry("container-access", "Prevents opening containers such as chests, furnaces and barrels."),
            Map.entry("bucket-fill", "Prevents scooping fluids with a bucket."),
            Map.entry("bucket-empty", "Prevents emptying buckets to place fluids."),
            Map.entry("armor-stand", "Prevents manipulating or breaking armor stands."),
            Map.entry("hanging-break", "Prevents breaking item frames and paintings."),
            Map.entry("hanging-place", "Prevents placing item frames and paintings."),
            Map.entry("vehicle-place", "Prevents placing boats and minecarts."),
            Map.entry("vehicle-destroy", "Prevents destroying boats and minecarts."),
            Map.entry("crop-trample", "Prevents trampling farmland and turtle eggs."),
            Map.entry("redstone", "Prevents redstone current changes inside the region."),
            Map.entry("piston", "Prevents pistons extending or retracting into the region."),
            Map.entry("fire-ignite", "Prevents players igniting fire with flint and steel."),
            Map.entry("fire-spread", "Prevents fire spreading, blocks burning and non-player ignitions."),
            Map.entry("fluid-flow", "Prevents water and lava flowing into the region."),
            Map.entry("leaf-decay", "Prevents natural leaf decay."),
            Map.entry("block-explosion", "Prevents block damage from block-based explosions like beds and anchors."),
            Map.entry("entity-explosion", "Prevents block damage from entity explosions like creepers and TNT."),
            Map.entry("mob-spawning", "Prevents natural mob spawns inside the region."),
            Map.entry("mob-griefing", "Prevents mobs altering blocks or trampling crops and turtle eggs."),
            Map.entry("damage-animals", "Prevents players damaging animals."),
            Map.entry("mob-damage", "Prevents mobs and other entities damaging players."),
            Map.entry("pvp", "Prevents player-vs-player combat, projectiles included."),
            Map.entry("invincible", "Makes players inside immune to all damage."),
            Map.entry("fall-damage", "Prevents fall damage inside the region."),
            Map.entry("hunger", "Freezes hunger loss inside the region."),
            Map.entry("item-drop", "Prevents dropping items."),
            Map.entry("item-pickup", "Prevents picking up items."),
            Map.entry("enderpearl", "Prevents teleporting into the region with ender pearls."),
            Map.entry("chorus-fruit", "Prevents teleporting into the region by eating chorus fruit."),
            Map.entry("keep-inventory", "Keeps inventory and XP on death inside the region."),
            Map.entry("exp-drop", "Removes the XP orbs from deaths inside the region."),
            Map.entry("chat", "Prevents players chatting while inside the region."),
            Map.entry("elytra", "Prevents players starting to glide with an elytra inside."),
            Map.entry("fly", "Prevents survival or adventure players starting to fly inside."),
            Map.entry("totem", "Prevents totems of undying from saving players inside."),
            Map.entry("command-blacklist", "Comma-separated list of command names blocked inside the region."),
            Map.entry("ride", "Prevents mounting vehicles and rideable entities."),
            Map.entry("sleep", "Prevents sleeping in a bed."),
            Map.entry("respawn-anchor", "Prevents charging or using respawn anchors."),
            Map.entry("item-frame-rotation", "Prevents rotating the item displayed in an item frame."),
            Map.entry("use-anvil", "Prevents opening anvils."),
            Map.entry("beacon", "Prevents opening beacons."),
            Map.entry("villager-trade", "Prevents trading with villagers and wandering traders."),
            Map.entry("shear", "Prevents shearing sheep, mooshrooms and snow golems."),
            Map.entry("leash", "Prevents leashing entities with a lead."),
            Map.entry("animal-breeding", "Prevents breeding animals."),
            Map.entry("sign-edit", "Prevents editing sign text."),
            Map.entry("fishing-hook", "Prevents reeling in entities or items with a fishing rod."),
            Map.entry("projectile-launch", "Prevents firing projectiles like arrows, tridents and snowballs."),
            Map.entry("receive-chat", "Prevents players inside the region from receiving chat messages."),
            Map.entry("command-whitelist", "List of the only command roots allowed inside the region."),
            Map.entry("deny-message", "Custom message shown instead of the generic denial message for refused actions."),
            Map.entry("entry-deny-message", "Custom message shown when entry to the region is refused."),
            Map.entry("exit-deny-message", "Custom message shown when leaving the region is refused."),
            Map.entry("farewell-title", "Title line shown when a player leaves the region."),
            Map.entry("farewell-subtitle", "Subtitle line shown when a player leaves the region."),
            Map.entry("lightning", "Prevents lightning striking inside the region."),
            Map.entry("lava-fire", "Prevents lava setting nearby blocks on fire."),
            Map.entry("water-flow", "Prevents water flowing inside the region."),
            Map.entry("lava-flow", "Prevents lava flowing inside the region."),
            Map.entry("fire-burn", "Prevents fire consuming blocks."),
            Map.entry("block-spread", "Prevents non-fire spreading like grass, mycelium, mushrooms, vines and sculk."),
            Map.entry("snow-fall", "Prevents snow layers forming."),
            Map.entry("snow-melt", "Prevents snow layers melting."),
            Map.entry("ice-form", "Prevents ice forming."),
            Map.entry("ice-melt", "Prevents ice melting."),
            Map.entry("frosted-ice-form", "Prevents frost-walker frosted ice forming."),
            Map.entry("frosted-ice-melt", "Prevents frost-walker frosted ice melting."),
            Map.entry("soil-dry", "Prevents farmland reverting to dirt."),
            Map.entry("coral-fade", "Prevents coral dying out of water."),
            Map.entry("snowman-trails", "Prevents snow golems leaving snow trails."),
            Map.entry("crop-growth", "Prevents crops, sugar cane, cactus, bamboo and stems from growing."),
            Map.entry("tree-growth", "Prevents saplings growing into trees."),
            Map.entry("mushroom-growth", "Prevents mushrooms growing into huge mushrooms."),
            Map.entry("vine-growth", "Prevents vines spreading."),
            Map.entry("grass-spread", "Prevents grass spreading."),
            Map.entry("mycelium-spread", "Prevents mycelium spreading."),
            Map.entry("sculk-growth", "Prevents sculk and sculk veins spreading."),
            Map.entry("bone-meal", "Prevents using bone meal."),
            Map.entry("entity-transform", "Prevents entity transformations like zombie-villager cures and piglin zombification."),
            Map.entry("animal-spawning", "Prevents passive animals spawning."),
            Map.entry("monster-spawning", "Prevents hostile monsters spawning."),
            Map.entry("spawner-spawning", "Prevents mob spawners spawning mobs."),
            Map.entry("phantom-spawning", "Prevents phantoms spawning."),
            Map.entry("slime-spawning", "Prevents slimes and magma cubes spawning."),
            Map.entry("natural-spawning", "Prevents natural world spawns."),
            Map.entry("egg-spawning", "Prevents spawn eggs spawning mobs."),
            Map.entry("command-spawning", "Prevents mobs spawned by /summon and plugins."),
            Map.entry("raid-spawning", "Prevents raid and village mobs spawning."),
            Map.entry("patrol-spawning", "Prevents pillager patrols spawning."),
            Map.entry("portal-spawning", "Prevents nether-portal spawns like zombified piglins."),
            Map.entry("deny-spawn", "List of explicit entity types blocked from spawning here."),
            Map.entry("villager-damage", "Prevents players damaging villagers."),
            Map.entry("monster-damage", "Prevents players damaging monsters."),
            Map.entry("pet-damage", "Prevents damaging tamed pets."),
            Map.entry("firework-damage", "Prevents firework blast damage to entities."),
            Map.entry("entity-explosion-damage", "Prevents explosion damage to entities and players."),
            Map.entry("creeper-explosion", "Prevents block damage from creeper explosions."),
            Map.entry("tnt", "Prevents block damage from TNT explosions."),
            Map.entry("ghast-fireball", "Prevents block damage from ghast fireballs."),
            Map.entry("wither-damage", "Prevents block damage from the wither."),
            Map.entry("enderdragon-block-damage", "Prevents block damage from the ender dragon."),
            Map.entry("potion-splash", "Prevents splash and lingering potions taking effect inside."),
            Map.entry("melee-pvp", "Prevents melee player-vs-player combat."),
            Map.entry("projectile-pvp", "Prevents projectile player-vs-player combat."),
            Map.entry("door-use", "Prevents opening doors and fence gates."),
            Map.entry("trapdoor-use", "Prevents opening trapdoors."),
            Map.entry("button-use", "Prevents pressing buttons."),
            Map.entry("lever-use", "Prevents flipping levers."),
            Map.entry("pressure-plate-use", "Prevents triggering pressure plates."),
            Map.entry("ender-chest-use", "Prevents opening ender chests."),
            Map.entry("crafting-table-use", "Prevents opening crafting tables."),
            Map.entry("enchant-table-use", "Prevents opening enchanting tables."),
            Map.entry("break-spawners", "Prevents breaking mob spawners."),
            Map.entry("place-spawners", "Prevents placing mob spawners."),
            Map.entry("item-despawn", "Prevents dropped items from despawning."),
            Map.entry("item-merge", "Prevents dropped items from merging into stacks."),
            Map.entry("mob-drops", "Prevents mobs dying here from dropping items or XP."),
            Map.entry("block-drops", "Prevents blocks broken here from dropping items."),
            Map.entry("drop-on-death", "Prevents players dying here from dropping their items."),
            Map.entry("gamemode", "Sets the game mode applied while inside, restored on exit."),
            Map.entry("time-lock", "Sets a client-only time of day shown while inside, reset on exit."),
            Map.entry("weather-lock", "Sets client-only weather (clear or rain) while inside, reset on exit."),
            Map.entry("walk-speed", "Sets the walk speed (0.0-1.0) while inside, restored on exit."),
            Map.entry("fly-speed", "Sets the fly speed (0.0-1.0) while inside, restored on exit."),
            Map.entry("heal-amount", "Health added each interval to players inside (negative to poison)."),
            Map.entry("heal-delay", "Seconds between heal applications (default 2)."),
            Map.entry("heal-min-health", "Minimum health bound for the heal effect (default 0)."),
            Map.entry("heal-max-health", "Maximum health bound for the heal effect (default 20)."),
            Map.entry("feed-amount", "Food added each interval to players inside (negative to starve)."),
            Map.entry("feed-delay", "Seconds between feed applications (default 2)."),
            Map.entry("feed-min-hunger", "Minimum food bound for the feed effect (default 0)."),
            Map.entry("feed-max-hunger", "Maximum food bound for the feed effect (default 20)."),
            Map.entry("glow", "Makes players glow while inside the region."),
            Map.entry("experience-multiplier", "Multiplies XP gained inside the region (0 = none, 2 = double)."),
            Map.entry("portal-use", "Prevents using nether and end portals."),
            Map.entry("move", "Freezes players in place, preventing movement inside."),
            Map.entry("teleport-in", "Prevents teleporting into the region."),
            Map.entry("teleport-out", "Prevents teleporting out of the region."),
            Map.entry("fire-damage", "Prevents burning damage to players inside."),
            Map.entry("lava-damage", "Prevents lava damage to players inside."),
            Map.entry("drowning-damage", "Prevents drowning damage to players inside."),
            Map.entry("suffocation-damage", "Prevents suffocation damage to players inside blocks."),
            Map.entry("contact-damage", "Prevents cactus, sweet-berry and stalagmite contact damage."),
            Map.entry("void-damage", "Prevents void damage to players (they keep falling)."),
            Map.entry("freeze-damage", "Prevents powder-snow freezing damage to players inside."),
            Map.entry("starvation-damage", "Prevents starvation damage at empty hunger."),
            Map.entry("lightning-damage", "Prevents lightning-strike damage to players inside."),
            Map.entry("dragon-breath-damage", "Prevents ender dragon breath cloud damage to players."),
            Map.entry("hot-floor-damage", "Prevents magma-block damage to players standing on them."),
            Map.entry("fly-into-wall-damage", "Prevents elytra kinetic damage from flying into walls."),
            Map.entry("cramming-damage", "Prevents entity-cramming damage to players inside."),
            Map.entry("entry", "Prevents players entering the region."),
            Map.entry("exit", "Prevents players leaving the region."),
            Map.entry("greeting", "Message shown to players entering the region."),
            Map.entry("farewell", "Message shown to players leaving the region."),
            Map.entry("title", "Title line shown to players entering the region."),
            Map.entry("subtitle", "Subtitle line shown to players entering the region."),
            Map.entry("action-bar", "Action bar message shown to players entering the region.")
    );

    private FlagDescriptions() {
    }

    /** The English description for a flag key, or an empty string when unknown. */
    public static String get(String flagKey) {
        return BY_KEY.getOrDefault(flagKey, "");
    }
}
