package fr.maxlego08.zregions.common.selection;

import fr.maxlego08.zregions.common.platform.RegionLocation;
import fr.maxlego08.zregions.common.shape.CuboidShape;

import java.util.List;
import java.util.Optional;

/**
 * An immutable snapshot of a player's selection: two corner positions plus an
 * optional list of polygon vertices. Either position may be {@code null} while
 * the selection is in progress; shape derivation is handled by
 * {@link SelectionShapeBuilder}, which reads all three pieces.
 */
public final class Selection {

    private final RegionLocation pos1;
    private final RegionLocation pos2;
    private final List<RegionLocation> points;

    public Selection(RegionLocation pos1, RegionLocation pos2) {
        this(pos1, pos2, List.of());
    }

    public Selection(RegionLocation pos1, RegionLocation pos2, List<RegionLocation> points) {
        this.pos1 = pos1;
        this.pos2 = pos2;
        this.points = List.copyOf(points);
    }

    public RegionLocation getPos1() {
        return this.pos1;
    }

    public RegionLocation getPos2() {
        return this.pos2;
    }

    /** The polygon vertices added with /rg addpoint (or generated by /rg star), in order. */
    public List<RegionLocation> getPoints() {
        return this.points;
    }

    public boolean isComplete() {
        return this.pos1 != null && this.pos2 != null;
    }

    public boolean isSameWorld() {
        return isComplete() && this.pos1.getWorldName().equals(this.pos2.getWorldName());
    }

    /** The world of the first defined position, or {@code null} for an empty selection. */
    public String getWorldName() {
        if (this.pos1 != null) {
            return this.pos1.getWorldName();
        }
        return this.pos2 != null ? this.pos2.getWorldName() : null;
    }

    /** The selected cuboid, present only when the selection is complete and in a single world. */
    public Optional<CuboidShape> toCuboid() {
        if (!isSameWorld()) {
            return Optional.empty();
        }
        return Optional.of(new CuboidShape(
                this.pos1.getBlockX(), this.pos1.getBlockY(), this.pos1.getBlockZ(),
                this.pos2.getBlockX(), this.pos2.getBlockY(), this.pos2.getBlockZ()));
    }
}
